language: ruby
rvm:
  - 2.1.1

addons:
  postgresql: "9.3"

before_install:
  - sudo apt-get update -qq && sudo apt-get install postgresql-server-dev-9.3

before_script:
  - psql -c 'create database chitter_test; create database chitter_development;' -U postgres

test:
  adapter: postgresql
  database: chitter_test
  username: postgres

script: bundle exec rspec